import type { Article, Tool, CustomPage } from './types'

/** Goedgekeurde content C001–C023 (CONTENT.md, 7 okt 2026). */
export const CONTENT_MIGRATION_VERSION = 3

export const OLD_DUMMY_ARTICLE_IDS = [
  'art_concert',
  'art_steenbrugge',
  'art_uitpas',
  'art_lili',
  'art_compagnons',
  'art_natuurpunt_drempels',
  'art_beernem',
  'art_kruidenier',
  'art_femma',
  'art_taranta',
  'art_natuurpunt_gids',
  'art_buddy',
  'art_christoff',
  'art_klaverveld',
  'art_ronin',
  'art_fietscursus',
] as const

export const OLD_DUMMY_TOOL_IDS = [
  'tool_takenblad',
  'tool_vrijwilligersfiche',
  'tool_quiz',
  'tool_sportned',
  'tool_tips',
  'tool_afspraken',
  'tool_brief',
  'tool_acties',
  'tool_checklist',
  'tool_uitpas',
  'tool_taaliconen',
  'tool_microlearning',
  'tool_voorbeeldflyer',
  'tool_ikdoemee',
  'tool_schrijfsimpel',
] as const

export const OLD_DUMMY_ARTICLE_TITLES = new Set([
  "Hoe zorgt het Concertgebouw ervoor dat mensen blijven deelnemen?",
  "Hoe maakt voetbalclub KSK Steenbrugge haar werking toegankelijk?",
  "Hoe werken zij met de UiTPAS?",
  "Hoe vindt Li Li een nieuw publiek?",
  "Hoe maakt Compagnons toegankelijke flyers?",
  "Welke drempels overwon Natuurpunt om anderstalige deelnemers aan te trekken?",
  "Hoe laat Beernem nieuwkomers een job vinden die past bij hun talenten?",
  "Hoe zorgt een sociale kruidenier voor passende vrijwilligerstaken?",
  "Hoe moedigt Femma deelnemers aan om (terug) te komen?",
  "Hoe organiseert Taranta vzw activiteiten samen met nieuwkomers?",
  "Hoe laat Natuurpunt deelnemers uitgroeien tot gids of bestuurslid?",
  "Hoe versterken een buddy en een nieuwkomer elkaar in Torhout?",
  "Hoe zet Residentie Christoff anderstalige vrijwilligers in?",
  "Hoe heeft wzc Klaverveld hun vrijwilligerspoule uitgebreid?",
  "Hoe zorgt een visie van een sportclub ervoor dat mensen zich welkom voelen?",
  "Hoe geef je fietscursussen aan volwassenen die nog niet goed Nederlands kunnen?",
])

export const OLD_DUMMY_TOOL_TITLES = new Set([
  "Takenblad voor vrijwilligers",
  "Sjabloon: vrijwilligersfiche",
  "Quiz: een warm welkom",
  "App: Sportned",
  "Tips: duidelijke taal in gesprekken",
  "Sjabloon: organisatieafspraken",
  "Voorbeeldbrief: inschrijving",
  "Acties: voor een warm welkom",
  "Checklist: hoe organiseer je de inschrijving in een sportclub?",
  "De UiTPAS",
  "Taaliconen",
  "Microlearning: hoe maak je een begrijpelijke flyer?",
  "Voorbeeldflyer: promotie voor jouw activiteit",
  "Website: ikdoemee.be",
  "Schrijf Simpel",
])

export const approvedArticles: Article[] = [
  {
    id: 'art_c002',
    title: "Waar werkt ons netwerk aan",
    slug: "waar-werkt-ons-netwerk-aan",
    description: "Het netwerk zet in op beeldvorming, ondersteuning van aanbieders en een warm onthaal.",
    source: "Gemeente Laarne",
    themes: ["Promotie en werving", "De eerste keren", "Betrokken deelname"],
    body: "Nieuwkomers laten deelnemen vraagt inzet op verschillende plekken. Wij doen mee rond Gent bundelt zijn aanpak rond drie uitdagingen: hoe we naar nieuwkomers kijken, hoe organisaties hun aanbod toegankelijk maken en hoe mensen de weg naar dat aanbod vinden.\n\nDe gemeentelijke netwerkpagina beschrijft acties rond getuigenisvideo’s, SamenLezen met Avansa, informatie en ondersteuning voor aanbieders, buddywerkingen en onthaal op maat met PIN vzw. Ook het voortzetten van de samenwerking krijgt aandacht. Lokale praktijken en bruikbare hulpmiddelen maken die aanpak concreet.\n\n[Lees de beschreven netwerkacties](https://www.laarne.be/wij-doen-mee-rond-gent)\n\n**Bron:** Gemeente Laarne. Gebaseerd op Wij doen mee rond Gent / Acties. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c003',
    title: "Brugwacht maakt ruimte voor ontmoeting in Wetteren",
    slug: "brugwacht-maakt-ruimte-voor-ontmoeting-in-wetteren",
    description: "Een buddyduo ontdekt samen de buurt en krijgt ondersteuning van de gemeente.",
    source: "Gemeente Wetteren",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "Bij Brugwacht ontmoet een Nederlandstalige inwoner van Wetteren of omgeving een anderstalige nieuwkomer. Samen kiezen ze activiteiten: wandelen, sporten, de bibliotheek bezoeken of een koffie drinken. Ze spreken minstens twee keer per maand af.\n\nDe gemeente begint met een gesprek over motivatie, verwachtingen en interesses. Daarna zoekt ze een passende match en begeleidt ze de start. Ook tijdens het traject blijft er opvolging. Gelijkwaardigheid staat centraal: een buddy deelt tijd en ervaringen en kan helpen om de weg naar een professionele dienst te vinden. Interesse? De gemeentepagina legt de werking en aanmeldmogelijkheden uit.\n\n[Ontdek Brugwacht in Wetteren](https://www.wetteren.be/buddywerking-brugwacht)\n\n**Bron:** Gemeente Wetteren. Gebaseerd op Brugwacht: buddywerking voor anderstalige nieuwkomers. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: true,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c004',
    title: "Brugpijler zoekt vrijwilligerswerk dat bij iemand past",
    slug: "brugpijler-zoekt-vrijwilligerswerk-dat-bij-iemand-past",
    description: "Wetteren begeleidt nieuwkomers naar vrijwilligerswerk vanuit hun interesses en talenten.",
    source: "Gemeente Wetteren",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "Een geschikte vrijwilligersplek begint bij de persoon die wil deelnemen. In Brugpijler bekijkt Wetteren samen met anderstalige nieuwkomers welke interesses en talenten zij willen inzetten. Het traject kan leiden naar een plek binnen gemeentelijke diensten of bij een andere organisatie.\n\nDe begeleiding omvat voorbereiding, persoonlijke ondersteuning en opvolging. Daardoor krijgt zowel de vrijwilliger als de ontvangende organisatie hulp bij de start. Voor aanbieders is dit een bruikbaar praktijkvoorbeeld van toeleiding op maat. Op de gemeentepagina staan meer uitleg, links naar getuigenissen en hulpmiddelen voor het werken met anderstalige vrijwilligers.\n\n[Lees hoe Brugpijler werkt](https://www.wetteren.be/vrijwilligerstraject-brugpijler)\n\n**Bron:** Gemeente Wetteren. Gebaseerd op Brugpijler: vrijwilligerstraject voor anderstalige nieuwkomers. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: true,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c005',
    title: "Deinze koppelt buddy’s op basis van gedeelde interesses",
    slug: "deinze-koppelt-buddys-op-basis-van-gedeelde-interesses",
    description: "Samen iets doen biedt een laagdrempelige aanleiding om elkaar beter te leren kennen.",
    source: "Stad Deinze",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "De buddywerking in Deinze brengt nieuwkomers en inwoners met elkaar in contact. Bij het koppelen van duo’s kijkt de stad naar gedeelde interesses. Die kunnen het vertrekpunt zijn voor activiteiten en gesprekken.\n\nVolgens de gemeentepagina spreken de buddy’s minstens twee keer per maand af, gedurende negen maanden. De ontmoeting helpt nieuwkomers om mensen en hun omgeving te leren kennen. Wie zich wil engageren, vindt op de pagina de lokale contactgegevens en een link om zich aan te melden. Voor andere organisaties biedt de aanpak inspiratie om een kennismaking te laten aansluiten bij wat beide deelnemers graag doen.\n\n[Bekijk de buddywerking in Deinze](https://www.deinze.be/buddywerking)\n\n**Bron:** Stad Deinze. Gebaseerd op Buddywerking. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: true,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c006',
    title: "Een buddy helpt nieuwkomers hun weg te vinden in Maldegem",
    slug: "een-buddy-helpt-nieuwkomers-hun-weg-te-vinden-in-maldegem",
    description: "In Maldegem kunnen nieuwkomers met een buddy Nederlands oefenen en het lokale aanbod ontdekken.",
    source: "Gemeente Maldegem",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "De buddywerking voor nieuwkomers in Maldegem vertrekt van een kennismaking met de betrokkenen. Een medewerker bespreekt verwachtingen en brengt het duo samen. Vervolgens krijgen de deelnemers tijd om elkaar en de buurt te leren kennen.\n\nDe gemeentepagina beschrijft een engagement van negen maanden en momenten voor uitwisseling. Samen kunnen de buddy’s Nederlands oefenen en vrijetijdsmogelijkheden ontdekken. Wie wil deelnemen, vindt de aanmeldinformatie bij de gemeente. Voor aanbieders is het een voorbeeld van een begeleide start, waarbij persoonlijk contact de brug vormt naar het lokale leven.\n\n[Ontdek het buddyproject in Maldegem](https://www.maldegem.be/buddyproject)\n\n**Bron:** Gemeente Maldegem. Gebaseerd op Buddyproject. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: true,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c007',
    title: "In Eeklo zijn beide deelnemers een buddy",
    slug: "in-eeklo-zijn-beide-deelnemers-een-buddy",
    description: "De buddywerking in Eeklo legt de nadruk op samen activiteiten kiezen en van elkaar leren.",
    source: "Stad Eeklo",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "Een Nederlandstalige Eeklonaar en een anderstalige nieuwe inwoner gaan samen op pad. Het duo kiest zelf wat het doet: sporten, een uitstap maken of bijpraten met een koffie. Regelmatig contact biedt ruimte om Nederlands te oefenen en het leven in Eeklo te ontdekken.\n\nEeklo benadrukt dat beide deelnemers iets van elkaar leren. De Nederlandstalige vrijwilliger krijgt ondersteuning van het lokaal bestuur. De huidige gemeentepagina beschrijft een engagement van één jaar, met groepsbijeenkomsten en evaluatie. Kandidaten vinden er een aanmeldlink; anderstalige inwoners kunnen contact opnemen met de taal- en inburgeringscoach.\n\n[Lees meer over Buddy in Eeklo](https://www.eeklo.be/buddywerking)\n\n**Bron:** Stad Eeklo. Gebaseerd op Buddy in Eeklo. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: true,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c008',
    title: "SamenLezen opent een gesprek zonder voorbereiding",
    slug: "samenlezen-opent-een-gesprek-zonder-voorbereiding",
    description: "Een verhaal of gedicht kan een toegankelijke aanleiding zijn om samen te praten en te luisteren.",
    source: "Avansa regio Gent",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "Bij SamenLezen leest een begeleider een tekst hardop. Op verschillende momenten is er ruimte voor gesprek: wat valt op, welke gedachten roept de tekst op? Deelnemers mogen meepraten en kunnen ook gewoon luisteren. Vooraf iets lezen of voorbereiden hoeft niet.\n\nAvansa regio Gent ondersteunt deze manier van samenkomen en biedt ook opleiding voor leesbegeleiders. Op de projectpagina staan groepen en praktische informatie. Organisaties die ontmoeting willen organiseren, kunnen er de methodiek leren kennen. Controleer bij de concrete groep welk taalniveau, welke locatie en welke deelnamevoorwaarden van toepassing zijn.\n\n[Ontdek SamenLezen bij Avansa](https://avansa-regiogent.be/projecten/samenlezen-algemeen)\n\n**Bron:** Avansa regio Gent. Gebaseerd op SamenLezen. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c009',
    title: "PIN ondersteunt toeleiding op maat binnen het netwerk",
    slug: "pin-ondersteunt-toeleiding-op-maat-binnen-het-netwerk",
    description: "Een persoonlijke match kan nieuwkomers helpen om een passende participatiekans te vinden.",
    source: "PIN vzw",
    themes: ["Inschrijving", "De eerste keren"],
    body: "PIN vzw beschrijft op zijn pagina over de vierde pijler een opdracht voor Wij doen mee rond Gent. De organisatie ondersteunt matching en toeleiding van nieuwkomers, in samenwerking met het Agentschap Integratie en Inburgering.\n\nVoor gemeenten en aanbieders biedt dit een aanknopingspunt wanneer iemand hulp nodig heeft om een activiteit of engagement te vinden dat bij hem of haar past. De partnerpagina licht de werking toe. Wil je weten hoe die ondersteuning in jouw gemeente georganiseerd wordt? Stem de actuele werkwijze en doorverwijzing af met de lokale netwerkcoördinatie.\n\n[Lees over de ondersteuning door PIN](https://pinvzw.be/vierde-pijler)\n\n**Bron:** PIN vzw. Gebaseerd op Vierde pijler. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c010',
    title: "Verwelkom een nieuwkomer als vrijwilliger in Deinze",
    slug: "verwelkom-een-nieuwkomer-als-vrijwilliger-in-deinze",
    description: "Deinze nodigt organisaties uit om anderstalige nieuwkomers een vrijwilligersplek te bieden.",
    source: "Stad Deinze",
    themes: ["Promotie en werving", "Betrokken deelname"],
    body: "Vrijwilligerswerk kan een gelegenheid zijn om mensen te leren kennen en Nederlands te oefenen. Op zijn netwerkpagina vraagt Deinze organisaties om anderstalige nieuwkomers te verwelkomen. De stad kan helpen zoeken naar een kandidaat en een passende taak.\n\nDe pagina noemt onder meer ondersteuning bij kinderopvang, middagactiviteiten op school en logistieke taken in een woonzorgcentrum. Dit zijn voorbeelden om het gesprek te openen over wat haalbaar is in jouw organisatie. De gemeentelijke contactpersoon kan samen met jou bekijken welke match past. De precieze afspraken worden afgestemd op de vrijwilliger en de ontvangende werking.\n\n[Bekijk hoe jouw organisatie kan meedoen in Deinze](https://www.deinze.be/wijdoenmeerondgent)\n\n**Bron:** Stad Deinze. Gebaseerd op Verwelkom een anderstalige nieuwkomer in je organisatie. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c011',
    title: "Lokale vrijwilligers verbinden nieuwkomers met Laarne en Kalken",
    slug: "lokale-vrijwilligers-verbinden-nieuwkomers-met-laarne-en-kalken",
    description: "Een vrijwilligersgroep combineert ondersteuning van mensen op de vlucht met contact in de gemeente.",
    source: "Werkgroep Vluchtelingen Laarne; bron Vluchtelingenwerk Vlaanderen",
    themes: ["Promotie en werving", "Betrokken deelname"],
    body: "De Werkgroep Vluchtelingen Laarne biedt volgens de fiche bij Vluchtelingenwerk Vlaanderen materiële, maatschappelijke en persoonlijke ondersteuning aan mensen met een vluchtachtergrond in Laarne en Kalken. De groep betrekt hen ook bij sociaal-culturele activiteiten.\n\nDaarnaast werkt de werkgroep aan bewustmaking bij inwoners en zoekt ze samenwerking met lokale verenigingen en handelaars. De fiche vermeldt samenwerking met de integratiedienst van het OCMW. Dit lokale voorbeeld kan organisaties inspireren om onthaal en deelname met elkaar te verbinden. De bronpagina bevat meer informatie en de contactgegevens van de werking.\n\n[Maak kennis met de werkgroep in Laarne](https://vluchtelingenwerk.be/werkgroep-vluchtelingen-laarne)\n\n**Bron:** Werkgroep Vluchtelingen Laarne; bron Vluchtelingenwerk Vlaanderen. Gebaseerd op Werkgroep Vluchtelingen Laarne. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c017',
    title: "Limburg laat zien hoe lokale en regionale buddybegeleiding samenwerken",
    slug: "limburg-laat-zien-hoe-lokale-en-regionale-buddybegeleiding-samenwerken",
    description: "Buddies Limburg verdeelt intake, matching en ondersteuning tussen lokale partners en regionale begeleiding.",
    source: "Vluchtelingenwerk Vlaanderen en lokale Limburgse partners",
    themes: ["De eerste keren", "Betrokken deelname"],
    body: "Buddies Limburg brengt nieuwkomers en vrijwilligers samen om mensen te ontmoeten en de buurt te ontdekken. De projectpagina beschrijft hoe RON en lokale partners, afhankelijk van de gemeente, de intake en matching opnemen. Vluchtelingenwerk Vlaanderen ondersteunt onder meer werving, vorming, intervisie en afstemming.\n\nVoor coördinatoren rond Gent biedt deze rolverdeling inspiratie: wie kent de deelnemers, wie begeleidt de vrijwilliger en wie zorgt voor uitwisseling tussen gemeenten? Het gaat om een Limburgse praktijk. Aanmelden of ondersteuning aanvragen gebeurt bij de daar genoemde partners, volgens hun eigen voorwaarden.\n\n[Lees over Buddies Limburg](https://vluchtelingenwerk.be/project/buddies-limburg)\n\n**Bron:** Vluchtelingenwerk Vlaanderen en lokale Limburgse partners. Gebaseerd op Buddyproject Limburg. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 'art_c022',
    title: "Maak de toegankelijkheid van je activiteit zichtbaar",
    slug: "maak-de-toegankelijkheid-van-je-activiteit-zichtbaar",
    description: "Heldere informatie over taal, voorzieningen en kosten helpt bezoekers hun deelname te plannen.",
    source: "publiq",
    themes: ["Promotie en werving", "Inschrijving"],
    body: "Toegankelijkheid gaat over verschillende drempels. publiq bundelt informatie over taaloefenkansen, voorzieningen voor mensen met een beperking en vrijetijdsparticipatie voor mensen in armoede.\n\nVoor organisatoren is de pagina een ingang om die informatie ook zichtbaar te maken bij hun aanbod. Denk aan taaliconen in de UiTdatabank en informatie over aanwezige voorzieningen. De pagina verwijst ook naar UiTPAS en sociaal tarief binnen de betrokken regio’s. Bekijk welke mogelijkheden voor jouw organisatie en activiteit gelden. Deel concrete, gecontroleerde informatie, zodat een bezoeker vooraf kan inschatten wat mogelijk is en waar hij of zij terechtkan met een vraag.\n\n[Bekijk de toegankelijkheidsinformatie van publiq](https://www.publiq.be/nl/projecten/uitnetwerk/uitnetwerk-partnerpagina/communicatie-en-promotie/gerichte-uit-communicatie/toegankelijkheid)\n\n**Bron:** publiq. Gebaseerd op Hoe toegankelijk is jouw evenement?. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    imageUrl: '',
    imageAlt: '',
    videoUrl: '',
    published: true,
    featured: false,
    faqs: [],
    relatedToolSlugs: [],
    createdAt: '2026-10-07T12:00:00.000Z',
    updatedAt: '2026-10-07T12:00:00.000Z',
  },
]

export const approvedTools: Tool[] = [
  {
    id: 'tool_c012',
    title: "Een toolkit voor werken met anderstalige vrijwilligers",
    slug: "een-toolkit-voor-werken-met-anderstalige-vrijwilligers",
    description: "Deze toolkit helpt organisaties om de start en begeleiding van anderstalige vrijwilligers voor te bereiden.",
    themes: ["De eerste keren", "Betrokken deelname"],
    imageUrl: '',
    imageAlt: '',
    body: "Wil je iemand die Nederlands leert als vrijwilliger verwelkomen? De toolkit van Vrijwilligerswerk Antwerpen en Atlas bespreekt hoe je een passende taak en ondersteuning organiseert. Het materiaal behandelt onder meer kennismaking, duidelijke communicatie, de eerste werkdag en opvolging.\n\nJe vindt er aandachtspunten om verwachtingen bespreekbaar te maken en rekening te houden met het Nederlands dat een taak vraagt. Gebruik de toolkit als hulpmiddel voor je team en stem afspraken af met de vrijwilliger. Wetteren verwijst naar deze externe publicatie vanuit Brugpijler. Via de link lees je de oorspronkelijke pdf van veertig pagina’s.\n\n**Bron / maker:** Vrijwilligerswerk Antwerpen en Atlas. Gebaseerd op Werken met anderstalige vrijwilligers Toolkit. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Lees de toolkit van Antwerpen en Atlas",
    downloadUrl: "https://www.wetteren.be/file/download/009c7f1c-a052-457e-979a-f0c19a94f29d/1gRSYPfju7sEGghC3VnZEuJzeJbxoJfxzN4ITmPouQ3d.pdf",
    externalUrl: '',
    faqs: [],
    published: true,
    order: 0,
  },
  {
    id: 'tool_c013',
    title: "Wegwijzer over vluchtelingen en vrijwilligerswerk",
    slug: "wegwijzer-over-vluchtelingen-en-vrijwilligerswerk",
    description: "Deze wegwijzer uit 2019 bundelt vragen over het begeleiden van vluchtelingen naar vrijwilligerswerk.",
    themes: ["Inschrijving", "Betrokken deelname"],
    imageUrl: '',
    imageAlt: '',
    body: "De Wegwijzer Vluchtelingen en Vrijwilligerswerk van Arteveldehogeschool is opgebouwd rond vijftien veelgestelde vragen. De publicatie helpt organisaties om praktische aandachtspunten te verkennen wanneer iemand met een vluchtachtergrond wil vrijwilligen.\n\nDe gids bevat ook onderwerpen zoals verblijfsstatuut en vergoeding. Omdat de uitgave uit 2019 dateert, gebruik je die onderdelen als achtergrond en controleer je actuele voorwaarden bij een bevoegde informatiebron. Voor de voorbereiding van een gesprek kan de gids nuttig zijn: welke vragen leven bij de vrijwilliger en welke afspraken moet de organisatie verduidelijken? Lees de oorspronkelijke uitgave via de downloadlink.\n\n**Bron / maker:** Arteveldehogeschool, 2019. Gebaseerd op Wegwijzer Vluchtelingen en Vrijwilligerswerk. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Lees de wegwijzer uit 2019",
    downloadUrl: "https://www.wetteren.be/file/download/2d9cd694-5daf-4d3e-bfa0-88fbdfed4bb8/2WOLFlzwj58L15Z1CXZG8I9zHnAQzG2FcV3kIKYAokI3d.pdf",
    externalUrl: '',
    faqs: [],
    published: true,
    order: 1,
  },
  {
    id: 'tool_c014',
    title: "Hoe volg je verandering in een buddyproject op",
    slug: "hoe-volg-je-verandering-in-een-buddyproject-op",
    description: "Dit workshopmateriaal helpt om na te denken over doelen, opvolging en evaluatie van buddywerkingen.",
    themes: ["Betrokken deelname"],
    imageUrl: '',
    imageAlt: '',
    body: "Hoe weet je wat een buddywerking betekent voor deelnemers? Jan Van Ongevalle en Peter De Cuyper van HIVA KU Leuven bespreken in dit workshopmateriaal verschillende manieren om verandering op te volgen. Naast vragenlijsten komen kwalitatieve methoden, zoals outcome mapping en het verzamelen van betekenisvolle veranderingen, aan bod.\n\nHet materiaal helpt coördinatoren om eerst hun evaluatievragen en beschikbare capaciteit te bepalen. Het maakt ook duidelijk dat veranderingen verschillende oorzaken kunnen hebben. Gebruik het als startpunt voor een aanpak die bij jouw werking past. Het document is een presentatie en bevat geen kant-en-klare evaluatie van ons netwerk.\n\n**Bron / maker:** HIVA KU Leuven; gepubliceerd via VVSG. Gebaseerd op Hoe meet ik de impact van mijn buddyproject?. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Bekijk het workshopmateriaal over impactmeting",
    downloadUrl: "https://www.vvsg.be/Leden/Diversiteit/Studiediedag%20inclucities/WS%204%20Impactmeting%20buddywerkingen_def.pdf",
    externalUrl: '',
    faqs: [],
    published: true,
    order: 2,
  },
  {
    id: 'tool_c015',
    title: "Vind activiteiten en ontmoetingen via ikdoemee.be",
    slug: "vind-activiteiten-en-ontmoetingen-via-ikdoemee-be",
    description: "Zoek een activiteit waarmee je Nederlands kunt oefenen, mensen kunt ontmoeten of als vrijwilliger kunt deelnemen.",
    themes: ["Promotie en werving", "Inschrijving", "De eerste keren"],
    imageUrl: '',
    imageAlt: '',
    body: "Op ikdoemee.be kun je zoeken op plaats en op wat je graag wilt doen. Het platform toont onder meer mogelijkheden om Nederlands te oefenen, nieuwe mensen te ontmoeten, vrijwilligerswerk te doen of een buddy te vinden.\n\nBekijk bij elke activiteit de concrete informatie over plaats, datum en taalniveau. Het aanbod verandert, dus controleer altijd de pagina van de activiteit voordat je inschrijft. Ook toeleiders kunnen het platform gebruiken om samen met een nieuwkomer mogelijkheden te verkennen. De link opent de Engelstalige versie van het platform.\n\n**Bron / maker:** ikdoemee.be. Gebaseerd op Ontmoet nieuwe mensen Oefen Nederlands. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Zoek een activiteit op ikdoemee.be",
    downloadUrl: '',
    externalUrl: "https://www.ikdoemee.be/en",
    faqs: [],
    published: true,
    order: 3,
  },
  {
    id: 'tool_c016',
    title: "Zoek een vrijwilligersgroep die werkt met mensen op de vlucht",
    slug: "zoek-een-vrijwilligersgroep-die-werkt-met-mensen-op-de-vlucht",
    description: "Het overzicht van Vluchtelingenwerk Vlaanderen helpt om lokale vrijwilligersinitiatieven te ontdekken.",
    themes: ["Promotie en werving", "De eerste keren"],
    imageUrl: '',
    imageAlt: '',
    body: "Vrijwilligersgroepen bieden op verschillende plaatsen ontmoeting en ondersteuning aan mensen op de vlucht. Vluchtelingenwerk Vlaanderen bundelt initiatieven in een overzicht met een provinciefilter en links naar hun werking.\n\nSelecteer Oost-Vlaanderen om relevante groepen in de ruimere regio te verkennen. Het overzicht vermeldt onder meer initiatieven in Gent en Laarne. Bekijk daarna de afzonderlijke fiche en neem contact op om te bespreken wat de groep momenteel aanbiedt. Dit is een handige vindplaats voor mogelijke samenwerking of doorverwijzing. De opname in dit overzicht betekent niet automatisch dat een organisatie lid is van Wij doen mee rond Gent.\n\n**Bron / maker:** Vluchtelingenwerk Vlaanderen. Gebaseerd op Vrijwilligersorganisaties voor mensen op de vlucht. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Zoek een lokale vrijwilligersgroep",
    downloadUrl: '',
    externalUrl: "https://vluchtelingenwerk.be/vrijwilligersorganisaties",
    faqs: [],
    published: true,
    order: 4,
  },
  {
    id: 'tool_c018',
    title: "Gastvrij Netwerk deelt ervaring met lokale vrijwilligerswerking",
    slug: "gastvrij-netwerk-deelt-ervaring-met-lokale-vrijwilligerswerking",
    description: "Deze toolkit uit 2018 bundelt ervaringen over het organiseren van vrijwilligerswerk voor mensen op de vlucht.",
    themes: ["Promotie en werving", "Betrokken deelname"],
    imageUrl: '',
    imageAlt: '',
    body: "Vrijwilligersgroepen zoeken hun plaats naast lokale diensten en andere organisaties. De informatiepagina over de toolkit van Gastvrij Netwerk beschrijft hoofdstukken over die rolverdeling, vrijwilligers werven en behouden, en samenwerking met de samenleving.\n\nDe toolkit bevat ook een checklist en thema’s uit het dagelijkse leven van mensen met een vluchtachtergrond. De tweede uitgave dateert uit 2018. Gebruik haar als bron van ervaring en bespreekvragen; controleer actuele rechten en procedures bij bevoegde diensten. Via de bronpagina kun je de publicatie en aanvullingen terugvinden. De toolkit is beschikbaar via Vluchtelingenwerk Vlaanderen.\n\n**Bron / maker:** Vluchtelingenwerk Vlaanderen en Gastvrij Netwerk. Gebaseerd op Toolkit Gastvrij Netwerk. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Bekijk de toolkit bij Vluchtelingenwerk",
    downloadUrl: '',
    externalUrl: "https://vluchtelingenwerk.be/toolkit-gastvrij-netwerk",
    faqs: [],
    published: true,
    order: 5,
  },
  {
    id: 'tool_c019',
    title: "Tien ingrediënten voor een toegankelijke vrijwilligerswerking",
    slug: "tien-ingredienten-voor-een-toegankelijke-vrijwilligerswerking",
    description: "Het Vlaams Steunpunt Vrijwilligerswerk biedt een publicatie om je vrijwilligerswerking inclusiever te maken.",
    themes: ["Promotie en werving", "De eerste keren", "Betrokken deelname"],
    imageUrl: '',
    imageAlt: '',
    body: "Hoe maak je ruimte voor vrijwilligers met verschillende achtergronden en mogelijkheden? De publicatie over tien ingrediënten voor een toegankelijke vrijwilligerswerking behandelt volgens het Vlaams Steunpunt Vrijwilligerswerk onder meer visie, communicatie, werving en ondersteuning.\n\nDit aanbod kan je team helpen om vragen over toegankelijkheid te bespreken en verbeterpunten te kiezen. Op de bronpagina staat hoe je de publicatie aanvraagt. Je vindt er ook een verwijzing naar een spel over vooroordelen in vrijwilligerswerk. Bekijk bij de aanbieder wat momenteel beschikbaar is en welke voorwaarden gelden. De hulpmiddelen zijn ontwikkeld door het steunpunt.\n\n**Bron / maker:** Vlaams Steunpunt Vrijwilligerswerk. Gebaseerd op Inclusief vrijwilligerswerk 10 ingrediënten voor een toegankelijke vrijwilligerswerking. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Bekijk het aanbod voor inclusief vrijwilligerswerk",
    downloadUrl: '',
    externalUrl: "https://www.vlaanderenvrijwilligt.be/vrijwilligersbeleid/werken-met-vrijwilligers/inclusief-vrijwilligerswerk/",
    faqs: [],
    published: true,
    order: 6,
  },
  {
    id: 'tool_c020',
    title: "Een checklist voor het eerste gesprek met een vrijwilliger",
    slug: "een-checklist-voor-het-eerste-gesprek-met-een-vrijwilliger",
    description: "Deze checklist helpt je om verwachtingen en praktische afspraken bij de start te bespreken.",
    themes: ["Inschrijving", "De eerste keren"],
    imageUrl: '',
    imageAlt: '',
    body: "Een kennismakingsgesprek geeft de kandidaat-vrijwilliger en de organisatie ruimte om vragen te stellen. De checklist van het Vlaams Steunpunt Vrijwilligerswerk helpt om dat gesprek voor te bereiden: hoe vond iemand de organisatie, wat wil die doen en welke uitleg is nodig?\n\nDe pdf bevat ook suggesties voor een intakeformulier, zoals interesses, talenten, beschikbaarheid en mogelijke drempels. Voor eenmalige engagementen of een proefmoment staat er een kortere versie in. Gebruik de checklist als houvast en pas het gesprek aan de persoon aan. De oorspronkelijke download telt twee pagina’s.\n\n**Bron / maker:** Vlaams Steunpunt Vrijwilligerswerk. Gebaseerd op Checklist kennismaking en intake. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Lees de checklist voor kennismaking en intake",
    downloadUrl: "https://www.vlaanderenvrijwilligt.be/wp-content/uploads/2025/05/Checklist-kennismakingsgesprek.pdf",
    externalUrl: '',
    faqs: [],
    published: true,
    order: 7,
  },
  {
    id: 'tool_c021',
    title: "Taaliconen helpen deelnemers een passende activiteit kiezen",
    slug: "taaliconen-helpen-deelnemers-een-passende-activiteit-kiezen",
    description: "Maak duidelijk hoeveel Nederlands iemand nodig heeft om aan jouw activiteit deel te nemen.",
    themes: ["Promotie en werving", "Inschrijving"],
    imageUrl: '',
    imageAlt: '',
    body: "Wie Nederlands leert, zoekt soms een activiteit om de taal buiten de les te oefenen. Taaliconen geven aan hoeveel kennis van het Nederlands een activiteit vraagt. Daarmee kunnen deelnemers beter inschatten of het aanbod bij hen past.\n\npubliq legt uit hoe organisatoren taaliconen gebruiken in de UiTdatabank. De bron vermeldt dat je eerst een vorming over duidelijke taal en taaliconen volgt en verwijst naar een e-learning en een handleiding. Gebruik taaliconen samen met begrijpelijke praktische informatie. Bekijk de actuele instructies bij publiq voordat je iconen toekent aan je aanbod.\n\n**Bron / maker:** publiq in samenwerking met taalpartners. Gebaseerd op Taaliconen cultuur en vrije tijd als taaloefenkans. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Lees hoe je taaliconen gebruikt",
    downloadUrl: '',
    externalUrl: "https://www.publiq.be/nl/inzichten-en-praktijk/taaliconen-cultuur-en-vrije-tijd-als-taaloefenkans",
    faqs: [],
    published: true,
    order: 8,
  },
  {
    id: 'tool_c023',
    title: "Werk stap voor stap aan je vrijwilligersbeleid",
    slug: "werk-stap-voor-stap-aan-je-vrijwilligersbeleid",
    description: "Het Vlaams Steunpunt Vrijwilligerswerk bundelt hulpmiddelen voor de verschillende momenten in een vrijwilligerswerking.",
    themes: ["Promotie en werving", "De eerste keren", "Betrokken deelname"],
    imageUrl: '',
    imageAlt: '',
    body: "Van vrijwilligers werven tot hen bedanken en een engagement afronden: een werking vraagt aandacht op verschillende momenten. De overzichtspagina van het Vlaams Steunpunt Vrijwilligerswerk verwijst naar thema’s zoals visie, onthaal, waardering, inclusie en talentgericht vrijwilligerswerk.\n\nJe kunt deze wegwijzer gebruiken om te kiezen welk onderdeel jouw organisatie eerst wil verbeteren. Voor een eerste kennismakingsgesprek of inclusieve werving vind je op onze website ook afzonderlijke verwijzingen naar hulpmiddelen van hetzelfde steunpunt. De aanbieder meldt dat oudere publicaties worden vernieuwd. Gebruik daarom bij voorkeur de actuele verwijzingen op de bronpagina.\n\n**Bron / maker:** Vlaams Steunpunt Vrijwilligerswerk. Gebaseerd op Werken met vrijwilligers. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
    summary: [],
    downloadLabel: "Bekijk de wegwijzer voor vrijwilligersbeleid",
    downloadUrl: '',
    externalUrl: "https://www.vlaanderenvrijwilligt.be/vrijwilligersbeleid/werken-met-vrijwilligers/",
    faqs: [],
    published: true,
    order: 9,
  },
]

// Relate articles to tools that share at least one theme
for (const a of approvedArticles) {
  const slugs: string[] = []
  for (const t of approvedTools) {
    if (t.themes.some((th) => a.themes.includes(th)) && !slugs.includes(t.slug)) slugs.push(t.slug)
  }
  a.relatedToolSlugs = slugs.slice(0, 4)
}

export const approvedOverOnsPage: CustomPage = {
  id: 'page_c001',
  title: "Wij doen mee rond Gent verbindt nieuwkomers en hun buurt",
  slug: 'over-ons',
  type: 'custom',
  bannerTitle: "Wij doen mee rond Gent verbindt nieuwkomers en hun buurt",
  bannerIntro: "Ons netwerk helpt anderstalige nieuwkomers om mensen te ontmoeten en deel te nemen aan het lokale leven.",
  body: "Wij doen mee rond Gent brengt zestien lokale besturen en partners samen. Deinze neemt het netwerkleiderschap op. We werken aan een toegankelijk aanbod waarmee anderstalige nieuwkomers hun sociale netwerk kunnen uitbreiden.\n\nDat aanbod kan verschillende vormen aannemen, zoals een buddytraject, vrijwilligerswerk of een activiteit in de buurt. Het netwerk richt zich ook tot nieuwkomers die vrijwillig willen deelnemen. Gemeenten en organisaties verbinden hun kennis en aanbod om de stap naar ontmoeting kleiner te maken.\n\n[Bekijk het netwerk bij Europa WSE](https://www.europawse.be/ons-aanbod/inburgering/wij-doen-mee)\n\n**Bron:** Europa WSE en netwerk Wij doen mee rond Gent. Gebaseerd op Wij doen mee / Regio Gent. Eigen samenvatting met verwijzing naar de oorspronkelijke bron.\n",
  published: true,
  showInNav: true,
  order: 1,
}

