import type { CmsData } from './types'
import { uid } from './types'
import {
  approvedArticles,
  approvedTools,
  approvedOverOnsPage,
} from './approvedContent'

const IMG = {
  thema0: '/images/9e9b4e51-a717-4587-9957-06d19d265a2d.jpg',
  thema1: '/images/63587b3b-149b-47b8-9f76-2e8bfcd21a80.jpg',
  thema2: '/images/7343e54b-d84e-4793-a58a-52a973624c81.jpg',
  thema3: '/images/e2eedfaa-65b6-4f2a-9f77-0f356b35de97.jpg',
  art0: '/images/7dfb2392-13f0-460d-b1bf-7361db8613b6.jpg',
  art1: '/images/49663b60-651a-4401-9574-bce482a078c4.jpg',
  art2: '/images/9544e5ff-b134-4906-a452-9745ff8f0f1f.jpg',
  art3: '/images/56f8b53b-1040-4c6e-b339-f91c80d97b49.jpg',
  art4: '/images/3f79c3d2-2dac-428a-b4aa-01b9cb73430a.jpg',
  art5: '/images/ca7bf843-c909-417c-b969-5b3529fb4984.png',
  art6: '/images/d2bf960f-2bd6-4ef3-ba0a-e191dbf78d68.jpg',
  art7: '/images/f037c54a-e4a7-4b20-ba0a-19d6669d1e6d.png',
  art8: '/images/ba5bf100-7bd5-4edc-b735-c23b001a3b05.png',
  art9: '/images/70952f56-2576-4027-80e2-5201877a5180.jpg',
  art10: '/images/3f98a6be-3e76-466b-8244-12471f5e8ed3.jpg',
  art11: '/images/419a4d97-330e-4b6f-91a1-c8aa9bb8ab7f.png',
  tool0: '/images/ccf16716-24b4-499c-91c2-d7233808f67e.jpg',
  tool1: '/images/2bb61f24-ed15-4653-8d95-77529ee6b77a.png',
  tool2: '/images/c6297b62-43b7-4b6d-93d7-3ea52e53c5d9.jpg',
  tool3: '/images/b9fb9add-24a5-48db-8b56-3bd82956b895.jpg',
  tool4: '/images/a75fe5ff-c7a9-4dd4-bc53-9abab5fc95c9.jpg',
  tool5: '/images/063966c0-f4bf-47d6-bf4a-3cb2dfd5304b.jpg',
  tool6: '/images/833c4689-bb36-4687-a015-faa8f3106a53.jpg',
  tool7: '/images/33c1ecc4-4424-4982-8141-d3c7d700efc4.jpg',
  tool8: '/images/fa04be68-9b64-4c2a-9942-94ec6234a7fa.jpg',
  tool9: '/images/1c06c7da-2a5e-41dd-a398-fdd2bf37a1c7.jpg',
  tool10: '/images/41d038dc-feaa-4529-b1a6-f18a09495d12.jpg',
  tool11: '/images/38ad1254-626a-4870-8d34-0e94605102d2.jpg',
  femma: '/images/db6286fb-a27a-4a8a-bbbb-52a58a658502.jpg',
  uitpas: '/images/ccf16716-24b4-499c-91c2-d7233808f67e.jpg',
  steenbrugge: '/images/ca7bf843-c909-417c-b969-5b3529fb4984.png',
  concert: '/images/f037c54a-e4a7-4b20-ba0a-19d6669d1e6d.png',
  lili: '/images/419a4d97-330e-4b6f-91a1-c8aa9bb8ab7f.png',
}

const now = new Date().toISOString()

export function createSeedData(): CmsData {
  const themes = [
    {
      id: 'theme_promotie',
      title: 'Promotie en werving',
      slug: 'promotie-en-werving',
      intro: "Het concept vrije tijd is voor anderstalige nieuwkomers soms onbekend. Hoe krijg je ze dan toch bij jouw organisatie? Hou je communicatie eenvoudig en breng je boodschap rechtstreeks naar de mensen.",
      imageUrl: IMG.thema0,
      imageAlt: 'groep mensen in sporthal',
      published: true,
      order: 0,
      faqs: [
        {
          id: uid('faq'),
          question: "Via welke kanalen bereik je nieuwkomers?",
          answer: "Anderstalige nieuwkomers bereik je, zoals andere doelgroepen, via een combinatie van verschillende kanalen.\n\n## Flyers\n\nEen flyer kan je rustig thuis bekijken, eventueel met de hulp van een ondersteuner of een vertaalapp. Het is bovendien een geheugensteun op het moment van de activiteit zelf.\n\nEen flyer bereikt ook mensen die beperkte digitale vaardigheden hebben en zij die minder toegang hebben tot een internetconnectie.\n\nWat zijn goede plaatsen om jouw flyers te verspreiden? Bijvoorbeeld bij de lokale supermarkt, het buurthuis, scholen …\n\nMaak een goede flyer met onze tools!\n\n## Digitaal\n\nRegistreer je activiteit op de website ikdoemee.be. Het werd speciaal ontwikkeld om anderstalige nieuwkomers het vrijetijdsaanbod te laten ontdekken.\nZet jij je activiteiten al in de UITdatabank? Goed nieuws, je kan ze automatisch publiceren op ikdoemee.be door taaliconen toe te voegen.\n\n## Toeleiders\n\nOmdat anderstalige nieuwkomers het vrijetijdsveld nog niet zo goed kennen, spelen toeleiders een belangrijke rol. Dat zijn medewerkers van het Agentschap Integratie en Inburgering, brugfiguren op school of medewerkers van je gemeente. Zij geven nieuwkomers meer context dan enkel een flyer. Ze beantwoorden ook algemene vragen rond vrije tijd. Betrek dus gerust gemeenteloketten en scholen in de buurt om je promotiemateriaal te verspreiden.\n\n## Snuffelmomenten\n\nToeleiders kunnen anderstalige nieuwkomers ook meenemen om jullie werking (ter plaatse) te leren kennen. Dat is voor deze doelgroep bijzonder interessant om te weten te komen hoe het er echt aan toe gaat in je organisatie.",
        },
        {
          id: uid('faq'),
          question: "Hoe zorg je ervoor dat iedereen jouw promotie begrijpt?",
          answer: "Het is belangrijk dat iedereen begrijpt wat je mag verwachten van de activiteit.\n\n## Duidelijke tekst\n\nBeperk je in je promotie tot de essentie. Gebruik duidelijk Nederlands in je teksten. Zo zijn mensen die nog niet zo goed Nederlands spreken makkelijk mee. Ook voor Nederlandstaligen is het heel fijn dat ze in één oogopslag alle belangrijke info zien.\n\nWil je je teksten snel omzetten naar duidelijke taal? Gebruik de website Schrijf Simpel.\n\n## Beelden\n\nGebruik echte foto's van jouw werking, die laten zien wat er gebeurt tijdens de activiteiten. Zo krijgen mensen een duidelijk en realistisch beeld.\n\n## Informatie\n\nVermeld essentiële informatie, zoals datum en tijdstip, locatie, doelgroep en prijs. Voeg altijd een contactpersoon met e-mailadres en telefoonnummer toe. Whatsapp is een heel toegankelijke communicatiemethode, ook voor deelnemers met beperkte digitale vaardigheden.\n\nOrganiseren jullie initiaties? Geef dat zeker mee in je communicatie!",
        },
        {
          id: uid('faq'),
          question: "Hoe laat je mensen kennismaken met jouw werking?",
          answer: "Het onbekende maakt het soms moeilijk om zomaar in te schrijven voor een heel jaar. Voor kinderen worden er vaak snuffeldagen georganiseerd. Waarom dan ook geen proeflessen voor volwassenen? Denk eventueel na over een tienbeurtenkaart. Dat maakt het engagement laagdrempeliger en je geeft nadien de mogelijkheid om nog in te schrijven voor het hele jaar.\n\nVeel gemeenten werken ook met toeleiders. Dat zijn medewerkers van het Agentschap Integratie en Inburgering, brugfiguren op school of medewerkers van je gemeente. Zij geven nieuwkomers meer context dan enkel een flyer. Ze beantwoorden ook algemene vragen rond vrije tijd. Breng hen op de hoogte van jouw initiatiemomenten.",
        },
      ],
      deepdives: [
        {
          id: uid('dd'),
          title: "Test je boodschap met focusgroepen",
          description: "Met de leidraad voor focusgroepen van de VGC en de VVSG verzamel je feedback om je communicatie nog sterker te maken.",
          buttonLabel: "Ga naar de leidraad voor focusgroepen",
          buttonUrl: "https://www.vvsg.be",
          imageUrl: "/images/fa04be68-9b64-4c2a-9942-94ec6234a7fa.jpg",
          imageAlt: "focusgroepen",
        },
        {
          id: uid('dd'),
          title: "Volg een vorming",
          description: "Wil je meer weten over duidelijke taal en toegankelijke vrije tijd?",
          buttonLabel: "Bekijk de kalender met vormingen van AgII",
          buttonUrl: "https://www.integratie-inburgering.be",
          imageUrl: "/images/1c06c7da-2a5e-41dd-a398-fdd2bf37a1c7.jpg",
          imageAlt: "vorming",
        },
        {
          id: uid('dd'),
          title: "Werking van Compagnie Cordial",
          description: "Wil jij je organisatie versterken met talentvolle nieuwkomers die jouw team diverser en inclusiever maken? Of een workshop op maat volgen? Bij CoCo ben je aan het juiste adres.",
          buttonLabel: "Ga naar de website van CoCo",
          buttonUrl: "https://www.compagniecordial.be",
          imageUrl: "/images/41d038dc-feaa-4529-b1a6-f18a09495d12.jpg",
          imageAlt: "Compagnie Cordial",
        },
      ],
    },
    {
      id: 'theme_inschrijving',
      title: 'Inschrijving',
      slug: 'inschrijving',
      intro: "Niet iedereen is handig met digitale tools of heeft voldoende kennis van het Nederlands. Organiseer daarom verschillende inschrijfmogelijkheden. Zo bereik je meer mensen, kiest iedereen wat best past en heet je mensen al vanaf de start welkom.",
      imageUrl: IMG.thema1,
      imageAlt: 'drie mensen aan tafel',
      published: true,
      order: 1,
      faqs: [
        {
          id: uid('faq'),
          question: "Hoe organiseer je de inschrijvingen?",
          answer: "Om zoveel mogelijk mensen te bereiken, zet je best in op een combinatie van een digitaal inschrijvingsformulier én een fysiek inschrijfmoment.\n\n## Digitaal formulier\n\n- Hou je inschrijvingsformulier zo kort en duidelijk mogelijk.\n- Maak een korte handleiding. Vermeld stap voor stap hoe je het formulier invult. Gebruik duidelijke taal en beelden zodat ook mensen die nog niet zo goed Nederlands spreken het begrijpen. Met de tool Schrijf Simpel kan je snel jouw tekst in duidelijke taal omzetten.\n- Vult de deelnemer niet alles in of gaat er iets fout? Voorzie een duidelijke melding. Zo weet de deelnemer wat te doen om toch succesvol in te schrijven.\n- Vermeld een contactpersoon, e-mailadres en telefoonnummer van jouw organisatie. Als mensen vragen hebben, kunnen ze die persoon mailen of whatsappen.\n\n## Fysiek inschrijfmoment\n\nTijdens het fysieke inschrijfmoment kun je meteen persoonlijk uitleg geven over de werking en een rondleiding geven. Zo verlaag je de drempel en maak je de inschrijving voor iedereen toegankelijk.\n\n- Wanneer? Richt één of meerdere inschrijfmomenten in. Noteer deze data op je flyers en in andere communicatie.\n- Waar? Laat de inschrijving doorgaan waar ook de activiteiten zelf plaatsvinden. Dan voelen nieuwe deelnemers zich al wat meer vertrouwd als ze voor het eerst naar de activiteit komen.\n- Aanspreekpunten aanstellen. Het is fijn als er één of meerdere aanspreekpunten zijn. Maak hen kenbaar door ze bijvoorbeeld een sticker of jas van de organisatie te geven. Idealiter komt deze persoon ook naar een eerste activiteit, zodat nieuwe deelnemers een vertrouwd gezicht zien.\n- Organisatieafspraken meegeven. Noteer alle afspraken over de organisatie en activiteiten zelf. Doe dat op papier, via e-mail en/of via whatsapp. Zo kan iedereen die rustig thuis bekijken, eventueel met de hulp van een ondersteuner of een vertaalapp. Gebruik de sjablonen en voorbeeldbrieven als inspiratie.\n\n## Kort op voorhand inschrijven\n\nVoor veel mensen is het lastig om lang op voorhand te plannen: een cursus Nederlands valt op een ander moment, een nieuwe job of kinderen die van school veranderen, verhuizen ... Daarom is het handig als je niet te lang op voorhand moet inschrijven. Dan is de kans groter dat het in de agenda past en dat mensen effectief komen!",
        },
        {
          id: uid('faq'),
          question: "Waarom is de UiTPAS interessant?",
          answer: "Met de UiTPAS bied je jouw activiteiten aan een voordeliger tarief aan voor mensen die recht hebben op een verhoogde tegemoetkoming.\n\nDeelnemers met een UiTPAS sparen punten bij elke activiteit. Ze kunnen deze inwisselen voor voordelen zoals korting, gadgets of gratis tickets. Als partner van de UiTPAS kies je zelf welke omruilvoordelen je aanbiedt.\n\nBovendien verschijnen jouw werking en activiteiten op de website van UiT in Vlaanderen, hun nieuwsbrief en sociale media. Op deze manier bereik je een bredere doelgroep en laat je je sociaal engagement zien.",
        },
        {
          id: uid('faq'),
          question: "Hoe kan je zonder inschrijving of met flexibele deelname werken?",
          answer: "Hoe vrijblijvender een activiteit is, hoe toegankelijker. De situatie van anderstalige nieuwkomers maakt dat hun agenda soms veranderlijk is. Bijvoorbeeld door een nieuwe job met verschillende uren, de cursus Nederlands, kinderen die van school veranderen ... De vrijheid om gewoon te kunnen komen, kan mensen motiveren.\n\nDe spontaniteit zorgt er ook voor dat er soms meer of minder mensen komen. Denk er dus goed over na of het een optie voor jullie is en of de infrastructuur het aankan. Is er genoeg materiaal voor een grotere groep mensen? Zijn er voldoende vrijwilligers om de activiteit te begeleiden?\n\nAls tussenoplossing kan je ook korte reeksen of een beurtenkaart aanbieden. Zo heb je meer planningszekerheid en toch voldoende flexibiliteit voor je deelnemers.\n\nBied je in je organisatie enkel een jaarwerking aan? Bekijk dan of het misschien mogelijk is om bijvoorbeeld twee keer per jaar snuffelmomenten (initiaties) in te plannen. Zo leren mensen je werking echt kennen en kunnen ze makkelijker kiezen voor een langer engagement.",
        },
        {
          id: uid('faq'),
          question: "Kan je gewoon Nederlands blijven spreken?",
          answer: "Voor mensen die Nederlands leren is het belangrijk om ook buiten de les te oefenen in alledaagse situaties.\n\n## Blijf daarom zo veel mogelijk Nederlands praten. Enkele tips:\n\n- Begin en eindig gesprekken altijd in het Nederlands.\n- Een taal oefenen gebeurt best in een positieve omgeving: laat iedereen weten dat het niet erg is als ze iets niet begrijpen of fouten maken.\n- Spreek net iets langzamer en duidelijker dan je gewoon bent, maar overdrijf niet. Dat maakt het makkelijker, maar zal voor Nederlandstaligen ook niet raar aanvoelen.\n- Gebruik je handen, gezichtsuitdrukkingen en voorwerpen. Doe een beweging voor terwijl je ook vertelt wat je aan het doen bent.\n- Geef je een uitleg en heb je het gevoel dat iemand het niet begrijpt? Voor veel mensen is het lastig om toe te geven dat ze iets niet begrijpen, vooral in een groep of met nieuwe gezichten. In een groep kan je beter wachten op een rustig één-op-éénmoment om dingen opnieuw uit te leggen. Probeer je boodschap anders te formuleren.\n\n## Vertaalapps gebruiken\n\nLukt het even niet? Geen paniek, vertaalapps zijn tegenwoordig best handig. Maar let op, soms maken ze nog fouten, zeker bij minder courante talen. Check altijd bij de deelnemer of de vertaling goed is overgekomen.\n\n## Andere talen gebruiken\n\nHet soepele verloop van de activiteit is prioritair! Soms kan het handig zijn om even een andere taal te gebruiken. Maak afspraken over wanneer je een andere taal gebruikt. Bijvoorbeeld in één-op-ééngesprekken of als je even bijpraat. Schakel nadien altijd terug over op het Nederlands.",
        },
      ],
      deepdives: [
        {
          id: uid('dd'),
          title: "Hoe toegankelijk is jouw vrijetijdsaanbod?",
          description: "Ontdek hoe ver jullie al staan op het vlak van toegankelijkheid. En waar je nog mee aan de slag kunt.",
          buttonLabel: "Doe de test!",
          buttonUrl: "https://www.integratie-inburgering.be",
          imageUrl: "/images/833c4689-bb36-4687-a015-faa8f3106a53.jpg",
          imageAlt: "toegankelijkheidstest",
        },
        {
          id: uid('dd'),
          title: "Volg een vorming",
          description: "Wil je meer weten over duidelijke taal en toegankelijke vrije tijd?",
          buttonLabel: "Bekijk de kalender met vormingen van AgII",
          buttonUrl: "https://www.integratie-inburgering.be",
          imageUrl: "/images/063966c0-f4bf-47d6-bf4a-3cb2dfd5304b.jpg",
          imageAlt: "vorming",
        },
      ],
    },
    {
      id: 'theme_eerste',
      title: 'De eerste keren',
      slug: 'de-eerste-keren',
      intro: "De eerste keer naar een nieuwe activiteit gaan is voor iedereen spannend, zowel voor de nieuwe deelnemers als voor de organisatie. Deze tips en tools helpen je om in te spelen op de noden van anderstaligen en nieuwkomers.",
      imageUrl: IMG.thema2,
      imageAlt: 'groep mensen buiten die applaudisseren',
      published: true,
      order: 2,
      faqs: [
        {
          id: uid('faq'),
          question: "Hoe zorg je ervoor dat iedereen zich welkom voelt?",
          answer: "Je welkom voelen is afhankelijk van veel factoren. Het begint met een open, vriendelijke en veilige sfeer: een glimlach doet wonderen.\n\n- Laat merken dat je echt interesse hebt in de deelnemers. Vraag bijvoorbeeld hoe hun dag was. Laat voelen dat het niet uitmaakt als je fouten in het Nederlands maakt. Lukt het nog niet om in het Nederlands een heel gesprek te voeren? Gebruik een vertaalapp, praat even in een andere taal of hou het op een korte, hartelijke uitwisseling zonder veel woorden.\n- Geef ook de praktische afspraken mondeling en schriftelijk mee: locatie, tijd en algemene regels, inclusief eventuele ongeschreven regels. Deze ongeschreven regels kunnen soms complex zijn.\n- Een compliment of bedankje zorgt altijd voor een goed gevoel, zoals: \"Leuk dat je meedoet!\". Dat geeft je ook de kans om mensen extra te motiveren om vaker aan te sluiten. Vraag of ze de volgende keer opnieuw komen en of ze al lid zijn van de Whatsappgroep.",
        },
        {
          id: uid('faq'),
          question: "Kan je gewoon Nederlands blijven spreken?",
          answer: "Voor mensen die Nederlands leren is het belangrijk om ook buiten de les te oefenen in alledaagse situaties.\n\n## Blijf daarom zo veel mogelijk Nederlands praten. Enkele tips:\n\n- Begin en eindig gesprekken altijd in het Nederlands.\n- Een taal oefenen gebeurt best in een positieve omgeving: laat iedereen weten dat het niet erg is als ze iets niet begrijpen of fouten maken.\n- Spreek net iets langzamer en duidelijker dan je gewoon bent, maar overdrijf niet. Dat maakt het makkelijker, maar zal voor Nederlandstaligen ook niet raar aanvoelen.\n- Gebruik je handen, gezichtsuitdrukkingen en voorwerpen. Doe een beweging voor terwijl je ook vertelt wat je aan het doen bent.\n- Geef je een uitleg en heb je het gevoel dat iemand het niet begrijpt? Voor veel mensen is het lastig om toe te geven dat ze iets niet begrijpen, vooral in een groep of met nieuwe gezichten. In een groep kan je beter wachten op een rustig één-op-éénmoment om dingen opnieuw uit te leggen. Probeer je boodschap anders te formuleren.\n\n## Vertaalapps gebruiken\n\nLukt het even niet? Geen paniek, vertaalapps zijn tegenwoordig best handig. Maar let op, soms maken ze nog fouten, zeker bij minder courante talen. Check altijd bij de deelnemer of de vertaling goed is overgekomen.\n\n## Andere talen gebruiken\n\nHet soepele verloop van de activiteit is prioritair! Soms kan het handig zijn om even een andere taal te gebruiken. Maak afspraken over wanneer je een andere taal gebruikt. Bijvoorbeeld in één-op-ééngesprekken of als je even bijpraat. Schakel nadien altijd terug over op het Nederlands.",
        },
        {
          id: uid('faq'),
          question: "Hoe ontvang je nieuwe deelnemers tijdens de eerste activiteiten?",
          answer: "## Zorg voor een aanspreekpunt\n\nBij de eerste activiteiten is het handig dat er iemand aanwezig is die laat zien hoe alles werkt en waar iedereen naartoe moet. Er moet geen aparte vrijwilliger zijn voor anderstalige nieuwkomers: één aanspreekpunt voor alle nieuwe deelnemers volstaat. Maak deze persoon herkenbaar, bijvoorbeeld met een opvallende sticker of jas.\n\n## Geef duidelijke instructies aan het aanspreekpunt\n\nLaat weten dat er anderstalige deelnemers komen en dat zij mogelijk extra uitleg nodig hebben. Vraag om net iets langzamer en duidelijker te spreken, zodat taalleerders goed kunnen volgen. Maak eventueel afspraken over tijdelijk een andere taal gebruiken.\n\n## Maak het contact persoonlijk\n\nHeb je een peter-, meter- of buddysysteem? Koppel nieuwe leden aan een enthousiast, ervaren lid. Persoonlijk contact verlaagt de drempel om vragen te stellen en helpt nieuwkomers om zich sneller thuis te voelen.\n\n## Follow-up na de activiteit\n\nVraag na de activiteit aan de nieuwe deelnemers hoe het gegaan is. Check of ze weten wanneer de volgende bijeenkomst plaatsvindt en of ze toegevoegd zijn aan de Whatsapp- of mailinggroep.",
        },
        {
          id: uid('faq'),
          question: "Moeten andere deelnemers weten dat er anderstalige nieuwkomers gaan meedoen?",
          answer: "Nee. Het is wel fijn als je de begeleider van de activiteit of de peter/meter/buddy meeneemt in het verhaal. Geef ze tips over duidelijke taal, vertaalapps of wat je van hen verwacht. Zij kunnen ook de brug naar andere deelnemers zijn. Laat ze weten wie er voor hen klaarstaat als ze zelf vragen hebben.\n\nHeb je het gevoel dat niet iedereen in je organisatie even enthousiast reageert op de nieuwe deelnemers? Spreek hen persoonlijk aan. Bespreek je gevoel met het bestuur of met professionals in je organisatie. Misschien kan je jouw koepelorganisatie om ondersteuning vragen?",
        },
      ],
      deepdives: [
        {
          id: uid('dd'),
          title: "Hoe leert een anderstalige Nederlands?",
          description: "Waarom leert de ene persoon sneller Nederlands dan de andere? Waarom maakt iemand vaak dezelfde fout?",
          buttonLabel: "Bekijk het filmpje",
          buttonUrl: "https://www.integratie-inburgering.be",
          imageUrl: "/images/b9fb9add-24a5-48db-8b56-3bd82956b895.jpg",
          imageAlt: "taalleren",
        },
        {
          id: uid('dd'),
          title: "Communicatiewaaier",
          description: "De communicatiewaaier is een praktische tool die hulp- en dienstverleners ondersteunt bij gesprekken met anderstaligen.",
          buttonLabel: "Ga naar communicatiewaaier.be",
          buttonUrl: "https://www.communicatiewaaier.be",
          imageUrl: "/images/a75fe5ff-c7a9-4dd4-bc53-9abab5fc95c9.jpg",
          imageAlt: "communicatiewaaier",
        },
        {
          id: uid('dd'),
          title: "Volg een vorming",
          description: "Wil je meer weten over duidelijke taal en toegankelijke vrije tijd?",
          buttonLabel: "Bekijk de kalender met vormingen van AgII",
          buttonUrl: "https://www.integratie-inburgering.be",
          imageUrl: "/images/c6297b62-43b7-4b6d-93d7-3ea52e53c5d9.jpg",
          imageAlt: "vorming",
        },
        {
          id: uid('dd'),
          title: "Meer praktische tips voor een warme ontvangst",
          description: "Ontdek enkele ijsbrekers voor een eerste activiteit op diversiteitspraktijk.be.",
          buttonLabel: "Lees het artikel",
          buttonUrl: "https://www.diversiteitspraktijk.be",
          imageUrl: "/images/3f98a6be-3e76-466b-8244-12471f5e8ed3.jpg",
          imageAlt: "ijsbrekers",
        },
      ],
    },
    {
      id: 'theme_betrokken',
      title: 'Betrokken deelname',
      slug: 'betrokken-deelname',
      intro: "Een vrijetijdsvereniging heeft betrokken deelnemers nodig om alles draaiende te houden. Hoe vergroot je de betrokkenheid van je leden of deelnemers? Hoe stimuleer je dat ze zich blijven inzetten?",
      imageUrl: IMG.thema3,
      imageAlt: 'vier mensen aan tafel in keuken',
      published: true,
      order: 3,
      faqs: [
        {
          id: uid('faq'),
          question: "Hoe motiveer je deelnemers om te blijven komen?",
          answer: "Nieuwe leden haken soms af zonder dat je weet waarom. Vaak heeft het niets te maken met je organisatie, maar verwachtte de deelnemer iets anders. Of misschien zijn er organisatorische uitdagingen, zoals de bereikbaarheid van de locatie of het tijdstip van de activiteit.\n\n## Vraag door\n\nVraag waarom iemand wel of niet terugkomt. Dat getuigt van oprechte interesse en geeft waardevolle inzichten.\nInvesteer in persoonlijk contact: een buddy of een aanspreekpunt die na de activiteit nog eens contact opneemt, zorgt voor extra verbinding.\n\n## Hou het contact warm\n\nEen groot engagement, zoals meteen voor een heel jaar inschrijven, kan afschrikken. Laat daarom altijd de deur op een kier staan: misschien past het nu niet, maar over een paar maanden wel. Stuur af en toe een berichtje over nieuwe activiteiten of nodig voormalige deelnemers uit voor een gezellig zomerfeestje. Whatsapp is de meest toegankelijke manier om te communiceren, ook voor mensen die minder digitaalvaardig zijn.\n\n## Zorg voor een aanspreekpunt\n\nHet aanspreekpunt is de trainer, de begeleider van de activiteit of iemand helemaal anders. Deelnemers kunnen bij het aanspreekpunt:\n\n- vragen stellen,\n- laten weten als ze niet kunnen deelnemen.",
        },
        {
          id: uid('faq'),
          question: "Hoe motiveer je deelnemers om mee te draaien in de organisatie?",
          answer: "Wie zich verbonden voelt met de organisatie, zal makkelijker meegaan in jouw verhaal. Een warm welkom, een warm contact en een praatje tussendoor leggen een goede basis om later te vragen of ze iets extra willen doen. Dat geldt ook voor de ouders van deelnemende kinderen in jouw vereniging.\n\n## Doseer\n\nOverval mensen niet meteen met grote verwachtingen. Zeg dat er ook kortere, afgebakende taken bestaan, bijvoorbeeld voor één dag, een weekend of een paar weken. Zo kunnen mensen zelf kiezen wat bij hen past en blijft de drempel laag.\n\n## Leg uit\n\n- Vertel concreet wat je verwacht.\n- Deel het werk op in duidelijke, haalbare taken. Voorzie een korte schriftelijke uitleg, liefst met beelden.\n- Geef aan dat perfect Nederlands niet nodig is. Talenten zijn belangrijker dan taalkennis.\n- Vertel dat iedereen binnen de organisatie vrijwilliger is. Voor veel anderstalige nieuwkomers is dit verrassend: pas als ze weten dat alles op vrijwilligers draait, begrijpen ze ook waarom hun hulp zo gewaardeerd is.\n\n## Geef keuze\n\nZorg voor een gevarieerd aanbod aan activiteiten: van technische ondersteuning tot helpen in de cafetaria. Denk samen na over welke taken het beste bij iemand passen. Is Nederlands spreken nog spannend? Dan zijn taken achter de schermen misschien meer geschikt.\n\nVeel lokale besturen hebben een vrijwilligerspunt die je hierbij ondersteunen.",
        },
      ],
      deepdives: [
        {
          id: uid('dd'),
          title: "Inspiratiegids 'werken met anderstalige vrijwilligers'",
          description: "Werken jullie al met anderstalige vrijwilligers? Of willen jullie graag meer anderstalige nieuwkomers als vrijwilliger verwelkomen binnen jullie organisatie? Dan is deze inspiratiegids van FMDO iets voor jou!",
          buttonLabel: "Ga naar de inspiratiegids van FMDO",
          buttonUrl: "https://www.fmdo.be",
          imageUrl: "/images/ccf16716-24b4-499c-91c2-d7233808f67e.jpg",
          imageAlt: "inspiratiegids FMDO",
        },
        {
          id: uid('dd'),
          title: "Werking van Compagnie Cordial",
          description: "Wil jij je organisatie versterken met talentvolle nieuwkomers die jouw team diverser en inclusiever maken? Of een workshop op maat volgen? Bij CoCo ben je aan het juiste adres.",
          buttonLabel: "Ga naar de website van CoCo",
          buttonUrl: "https://www.compagniecordial.be",
          imageUrl: "/images/38ad1254-626a-4870-8d34-0e94605102d2.jpg",
          imageAlt: "Compagnie Cordial",
        },
        {
          id: uid('dd'),
          title: "De Vlaamse Sportfederatie",
          description: "Als sportclub kan je rekenen op ondersteuning vanuit de Vlaamse Sportfederatie. Maak je lid en krijg toegang tot alle info uit hun kennisdatabank, bijvoorbeeld over vrijwilligersbeleid.",
          buttonLabel: "Ga naar de kennisdatabank",
          buttonUrl: "https://www.vlaamsesportfederatie.be",
          imageUrl: "/images/33c1ecc4-4424-4982-8141-d3c7d700efc4.jpg",
          imageAlt: "Vlaamse Sportfederatie",
        },
        {
          id: uid('dd'),
          title: "De Vrijwilligerscentrale helpt jouw organisatie!",
          description: "Zoek je als organisatie vrijwilligers? Heb je specifieke vragen over vrijwilligerswerk? Dan is de Vrijwilligerscentrale de geschikte plaats om even langs te gaan.",
          buttonLabel: "Ga naar de Vrijwilligerscentrale",
          buttonUrl: "https://www.vrijwilligerswerk.be",
          imageUrl: "/images/9544e5ff-b134-4906-a452-9745ff8f0f1f.jpg",
          imageAlt: "Vrijwilligerscentrale",
        },
      ],
    },
  ]

  const articles = approvedArticles.map((a) => ({ ...a }))

  const tools = approvedTools.map((t) => ({ ...t }))

const media: CmsData['media'] = Object.entries(IMG).map(([name, url]) => ({
    id: `media_${name}`,
    name,
    url,
    alt: name,
  }))

  return {
    version: 3,
    contentMigration: 3,
    settings: {
      siteName: 'Wij doen mee, rond Gent',
      logoLine1: 'Wij doen',
      logoLine2: 'mee,',
      logoLine3: 'rond Gent',
      homeTitle: 'Meer deelnemers voor jullie activiteiten?',
      homeIntro: 'Laat anderstalige nieuwkomers makkelijk deelnemen aan jouw vrijetijdsactiviteiten.\nOntdek tips, tools en inspiratie over hoe anderen het aanpakken.',
      homeSectionTitle: 'Laat je inspireren',
      homeSectionCta: 'Bekijk meer inspiraties',
      homeSectionCtaRoute: '/inspiratie',
      footerCopyright: '© 2026',
      footerCredit: 'gemaakt door Lieven :)',
      colors: {
        primary: '#188AD1',
        primaryDark: '#116296',
        accent: '#FECB01',
        secondary: '#FFF8DB',
        link: '#116296',
      },
    },
    nav: [
      { id: 'nav_home', label: 'Home', route: '/', order: 0 },
      { id: 'nav_tools', label: 'Tools', route: '/tools', order: 1 },
      { id: 'nav_inspiratie', label: 'Inspiratie', route: '/inspiratie', order: 2 },
    ],
    footerLinks: [
      { id: 'ft_contact', label: 'Contact', route: '/pagina/contact', order: 0 },
      { id: 'ft_over', label: 'Over ons', route: '/pagina/over-ons', order: 1 },
      { id: 'ft_disclaimer', label: 'Disclaimer', route: '/pagina/disclaimer', order: 2 },
      { id: 'ft_toegankelijk', label: 'Toegankelijkheidsverklaring', route: '/pagina/toegankelijkheid', order: 3 },
    ],
    themes,
    articles,
    tools,
    pages: [
      {
        id: 'page_contact',
        title: 'Contact',
        slug: 'contact',
        type: 'custom',
        bannerTitle: 'Contact',
        bannerIntro: 'Heb je een vraag? Neem gerust contact op.',
        body: "Mail ons via info@wijdoenmee.be.\\n\\nWe antwoorden zo snel mogelijk op werkdagen.\\n\\nWij doen mee, rond Gent helpt organisaties om anderstalige nieuwkomers makkelijker te laten deelnemen aan vrijetijdsactiviteiten.",
        published: true,
        showInNav: false,
        order: 0,
      },
      { ...approvedOverOnsPage, id: 'page_over' },
      {
        id: 'page_disclaimer',
        title: 'Disclaimer',
        slug: 'disclaimer',
        type: 'custom',
        bannerTitle: 'Disclaimer',
        bannerIntro: 'Juridische informatie over deze website.',
        body: "De inhoud van deze website is met zorg samengesteld. Toch kunnen we geen volledigheid of actualiteit garanderen.\n\nLinks naar externe sites vallen buiten onze verantwoordelijkheid.\n\nDeze privacyverklaring informeert je over welke persoonsgegevens we verzamelen, waarvoor we deze gebruiken en wat jouw rechten in dit verband zijn.\n\nWe vragen alleen persoonlijke gegevens (e-mailadres) als je het contactformulier invult. Bij jouw bezoek verzamelen we technische informatie via cookies.\n\nJe hebt altijd toegang tot je persoonsgegevens en kan ze laten verbeteren.",
        published: true,
        showInNav: false,
        order: 2,
      },
      {
        id: 'page_toegankelijk',
        title: 'Toegankelijkheidsverklaring',
        slug: 'toegankelijkheid',
        type: 'custom',
        bannerTitle: 'Toegankelijkheidsverklaring',
        bannerIntro: 'Onze engagementen rond digitale toegankelijkheid.',
        body: "We streven ernaar dat deze website toegankelijk is voor iedereen, inclusief mensen met een beperking.\n\nDit doen we in overeenstemming met de Europese richtlijn en het Vlaamse Bestuursdecreet. De richtlijnen die gevolgd worden zijn de Web Content Accessibility Guidelines (WCAG) 2.1 niveau AA.\n\nIedereen moet de informatie op deze website eenvoudig kunnen gebruiken en bekijken, dus ook slechtzienden, blinden, slechthorenden, doven en personen met een andere beperking.\n\nMeld problemen via info@wijdoenmee.be.",
        published: true,
        showInNav: false,
        order: 3,
      },
    ],
    media,
  }
}
